# SPDX-License-Identifier: GPL-2.0-only

include $(MSM_EXT_DISPLAY_ROOT)/config/kalamammdrivers.conf
LINUXINCLUDE += -include $(MSM_EXT_DISPLAY_ROOT)/config/kalamammdriversconf.h

obj-y += msm_ext_display.o

msm_ext_display-y := src/msm_ext_display.o
